# Generated by Django 3.1 on 2021-01-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollWikiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='lang',
            field=models.CharField(default='zh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiki',
            name='lang',
            field=models.CharField(default='zh', max_length=10),
            preserve_default=False,
        ),
    ]
